import type { Property, Agent } from "./types"

export const agents: Agent[] = [
  {
    id: "1",
    name: "Adaeze Okonkwo",
    email: "adaeze@abujapremier.com",
    phone: "+234 803 456 7890",
    whatsapp: "+2348034567890",
    avatar: "/professional-african-woman-real-estate-agent.jpg",
    company: "Abuja Premier Estates",
    verified: true,
  },
  {
    id: "2",
    name: "Chukwuemeka Ibe",
    email: "chukwuemeka@abujapremier.com",
    phone: "+234 806 789 0123",
    whatsapp: "+2348067890123",
    avatar: "/professional-african-man-real-estate-agent.jpg",
    company: "Abuja Premier Estates",
    verified: true,
  },
  {
    id: "3",
    name: "Fatima Abdullahi",
    email: "fatima@abujapremier.com",
    phone: "+234 809 012 3456",
    whatsapp: "+2348090123456",
    avatar: "/professional-african-woman-hijab-real-estate-agent.jpg",
    company: "Abuja Premier Estates",
    verified: true,
  },
]

export const properties: Property[] = [
  {
    id: "1",
    title: "Luxury 5-Bedroom Mansion with Pool",
    description:
      "An exquisite mansion in the heart of Maitama, featuring Italian marble floors, smart home technology, private swimming pool, landscaped gardens, and 24/7 security. Perfect for diplomats and executives seeking the finest living experience in Abuja.",
    price: 850000000,
    currency: "NGN",
    type: "house",
    status: "for-sale",
    bedrooms: 5,
    bathrooms: 6,
    area: 1200,
    areaUnit: "sqm",
    location: {
      address: "15 Aguiyi Ironsi Street",
      city: "Maitama",
      state: "Abuja FCT",
      coordinates: { lat: 9.0765, lng: 7.4919 },
    },
    features: ["Swimming Pool", "Smart Home", "Security", "Garden", "Garage", "BQ", "Gym"],
    images: [
      "/luxury-mansion-exterior-abuja-nigeria.jpg",
      "/luxury-mansion-living-room-modern-interior.jpg",
      "/luxury-mansion-swimming-pool-garden.jpg",
      "/luxury-mansion-master-bedroom-suite.jpg",
    ],
    agent: agents[0],
    createdAt: "2024-01-15",
    featured: true,
    views: 1247,
  },
  {
    id: "2",
    title: "Modern 3-Bedroom Apartment in Jabi",
    description:
      "Contemporary apartment with stunning city views, open-plan living, fitted kitchen, and premium finishes. Located in a secure estate with recreational facilities.",
    price: 180000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 3,
    bathrooms: 4,
    area: 250,
    areaUnit: "sqm",
    location: {
      address: "Jabi Lake Towers",
      city: "Jabi",
      state: "Abuja FCT",
      coordinates: { lat: 9.0444, lng: 7.4167 },
    },
    features: ["Lake View", "Gym", "Swimming Pool", "Concierge", "Parking", "Generator"],
    images: [
      "/modern-apartment-building-abuja-nigeria.jpg",
      "/modern-apartment-living-room-city-view.jpg",
      "/modern-kitchen-white-cabinets.jpg",
      "/modern-bedroom-minimalist-design.jpg",
    ],
    agent: agents[1],
    createdAt: "2024-01-20",
    featured: true,
    views: 892,
  },
  {
    id: "3",
    title: "Commercial Office Space - Central Business District",
    description:
      "Premium Grade A office space in the CBD. Open floor plan suitable for corporate headquarters, law firms, or financial institutions. High-speed elevators and backup power.",
    price: 15000000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 500,
    areaUnit: "sqm",
    location: {
      address: "Central Business District",
      city: "CBD",
      state: "Abuja FCT",
      coordinates: { lat: 9.0579, lng: 7.4951 },
    },
    features: ["24/7 Power", "High-speed Internet", "Elevator", "Security", "Parking", "Conference Room"],
    images: [
      "/modern-office-building-exterior-glass.jpg",
      "/modern-office-interior-open-plan.jpg",
      "/office-conference-room-modern.jpg",
      "/office-reception-area-professional.jpg",
    ],
    agent: agents[2],
    createdAt: "2024-02-01",
    featured: false,
    views: 456,
  },
  {
    id: "4",
    title: "Prime Land - Guzape District",
    description:
      "Strategic plot of land in the prestigious Guzape district. Ideal for residential development. All infrastructure in place including roads, drainage, and utilities.",
    price: 450000000,
    currency: "NGN",
    type: "land",
    status: "for-sale",
    area: 2000,
    areaUnit: "sqm",
    location: {
      address: "Guzape District",
      city: "Guzape",
      state: "Abuja FCT",
      coordinates: { lat: 9.0298, lng: 7.5156 },
    },
    features: ["Corner Plot", "C of O", "Tarred Road", "Electricity", "Water"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: agents[0],
    createdAt: "2024-02-10",
    featured: true,
    views: 623,
  },
  {
    id: "5",
    title: "Serviced 2-Bedroom Flat - Wuse 2",
    description:
      "Fully furnished and serviced flat with daily housekeeping. Perfect for business travelers and expatriates. Walking distance to restaurants and shopping.",
    price: 500000,
    currency: "NGN",
    type: "flat",
    status: "short-term",
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    areaUnit: "sqm",
    location: {
      address: "Plot 123, Aminu Kano Crescent",
      city: "Wuse 2",
      state: "Abuja FCT",
      coordinates: { lat: 9.0689, lng: 7.4745 },
    },
    features: ["Furnished", "Housekeeping", "WiFi", "Generator", "Security", "Parking"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: agents[1],
    createdAt: "2024-02-15",
    featured: false,
    views: 334,
  },
  {
    id: "6",
    title: "Student Hostel - Near University",
    description:
      "Well-maintained hostel accommodation near the University of Abuja. Single and shared rooms available. 24-hour security and reading room facilities.",
    price: 350000,
    currency: "NGN",
    type: "hostel",
    status: "for-rent",
    area: 25,
    areaUnit: "sqm",
    location: {
      address: "Near University of Abuja",
      city: "Gwagwalada",
      state: "Abuja FCT",
      coordinates: { lat: 8.9433, lng: 7.0833 },
    },
    features: ["Security", "Reading Room", "Water", "Electricity", "Laundry"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: agents[2],
    createdAt: "2024-02-20",
    featured: false,
    views: 289,
  },
  {
    id: "7",
    title: "4-Bedroom Terrace Duplex - Life Camp",
    description:
      "Elegant terrace duplex in a gated estate. Features include a spacious living area, modern kitchen, all rooms en-suite, and a private garden.",
    price: 95000000,
    currency: "NGN",
    type: "house",
    status: "for-sale",
    bedrooms: 4,
    bathrooms: 5,
    area: 300,
    areaUnit: "sqm",
    location: {
      address: "Dape Life Camp",
      city: "Life Camp",
      state: "Abuja FCT",
      coordinates: { lat: 9.0941, lng: 7.3839 },
    },
    features: ["Gated Estate", "Garden", "All Rooms En-suite", "Security", "Parking"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: agents[0],
    createdAt: "2024-02-25",
    featured: true,
    views: 567,
  },
  {
    id: "8",
    title: "Penthouse Apartment - Asokoro",
    description:
      "Exclusive penthouse with panoramic views of Abuja. Features include private elevator access, rooftop terrace, and world-class amenities.",
    price: 650000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 4,
    bathrooms: 5,
    area: 450,
    areaUnit: "sqm",
    location: {
      address: "Asokoro Extension",
      city: "Asokoro",
      state: "Abuja FCT",
      coordinates: { lat: 9.0333, lng: 7.5333 },
    },
    features: ["Private Elevator", "Rooftop Terrace", "Smart Home", "Concierge", "Wine Cellar", "Home Cinema"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: agents[1],
    createdAt: "2024-03-01",
    featured: true,
    views: 1089,
  },
  {
    id: "9",
    title: "Luxury Waterfront Villa - Mojidi Estate",
    description:
      "Stunning waterfront villa with private dock access. Features include infinity pool, home theater, wine cellar, and smart automation throughout.",
    price: 950000000,
    currency: "NGN",
    type: "house",
    status: "for-sale",
    bedrooms: 6,
    bathrooms: 7,
    area: 1500,
    areaUnit: "sqm",
    location: {
      address: "Mojidi Estate Waterfront",
      city: "Maitama",
      state: "Abuja FCT",
      coordinates: { lat: 9.075, lng: 7.48 },
    },
    features: ["Waterfront", "Private Dock", "Infinity Pool", "Home Theater", "Wine Cellar", "Smart Home"],
    images: ["/placeholder.svg?height=600&width=800", "/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-05",
    featured: true,
    views: 1450,
  },
  {
    id: "10",
    title: "Contemporary 4-Bedroom House - Katampe",
    description:
      "Modern 4-bedroom residential home with clean lines and sustainable design. Features solar panels, rainwater harvesting, and premium finishes.",
    price: 280000000,
    currency: "NGN",
    type: "house",
    status: "for-sale",
    bedrooms: 4,
    bathrooms: 4,
    area: 350,
    areaUnit: "sqm",
    location: {
      address: "Katampe Extension",
      city: "Katampe",
      state: "Abuja FCT",
      coordinates: { lat: 9.05, lng: 7.51 },
    },
    features: ["Solar Panels", "Rainwater Harvesting", "Modern Design", "Security", "Parking"],
    images: ["/placeholder.svg?height=600&width=800", "/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-08",
    featured: false,
    views: 234,
  },
  {
    id: "11",
    title: "Executive 5-Bedroom Mansion - Wuse Zone B",
    description:
      "Prestigious mansion with dedicated home office, library, and entertainment lounge. Premium security system and backup power.",
    price: 780000000,
    currency: "NGN",
    type: "house",
    status: "for-sale",
    bedrooms: 5,
    bathrooms: 6,
    area: 1100,
    areaUnit: "sqm",
    location: {
      address: "Wuse Zone B",
      city: "Wuse",
      state: "Abuja FCT",
      coordinates: { lat: 9.08, lng: 7.46 },
    },
    features: ["Home Office", "Library", "Entertainment Lounge", "Premium Security", "Generator", "Gym"],
    images: ["/placeholder.svg?height=600&width=800", "/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-03-10",
    featured: true,
    views: 890,
  },
  {
    id: "12",
    title: "Spacious 3-Bedroom Duplex - Garki",
    description:
      "Comfortable duplex with spacious rooms, modern kitchen, and dedicated staff quarters. Located in a well-developed area.",
    price: 165000000,
    currency: "NGN",
    type: "house",
    status: "for-sale",
    bedrooms: 3,
    bathrooms: 3,
    area: 280,
    areaUnit: "sqm",
    location: {
      address: "Garki II",
      city: "Garki",
      state: "Abuja FCT",
      coordinates: { lat: 9.035, lng: 7.495 },
    },
    features: ["Staff Quarters", "Modern Kitchen", "Security", "Parking"],
    images: ["/placeholder.svg?height=600&width=800", "/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-12",
    featured: false,
    views: 456,
  },
  {
    id: "13",
    title: "Luxury 2-Bedroom Apartment - Banex",
    description: "Modern apartment with high-end finishes, open-plan living, and stunning city skyline views.",
    price: 95000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 2,
    bathrooms: 2,
    area: 180,
    areaUnit: "sqm",
    location: {
      address: "Banex Plaza",
      city: "Banex",
      state: "Abuja FCT",
      coordinates: { lat: 9.04, lng: 7.43 },
    },
    features: ["City View", "Gym", "Parking", "Security", "Generator"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-14",
    featured: false,
    views: 345,
  },
  {
    id: "14",
    title: "Premium 4-Bedroom Apartment - Maitama",
    description: "Spacious corner apartment with premium materials, private balcony, and concierge service.",
    price: 380000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 4,
    bathrooms: 4,
    area: 380,
    areaUnit: "sqm",
    location: {
      address: "Maitama High Rise",
      city: "Maitama",
      state: "Abuja FCT",
      coordinates: { lat: 9.09, lng: 7.48 },
    },
    features: ["Corner Unit", "Private Balcony", "Concierge", "Gym", "Pool"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-03-16",
    featured: true,
    views: 678,
  },
  {
    id: "15",
    title: "Elegant Studio Apartment - Wuse 2",
    description: "Perfect for professionals. Fully furnished studio with kitchenette and modern amenities.",
    price: 45000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 1,
    bathrooms: 1,
    area: 90,
    areaUnit: "sqm",
    location: {
      address: "Wuse 2 Business District",
      city: "Wuse 2",
      state: "Abuja FCT",
      coordinates: { lat: 9.07, lng: 7.47 },
    },
    features: ["Furnished", "Kitchenette", "Security", "Parking"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-18",
    featured: false,
    views: 234,
  },
  {
    id: "16",
    title: "Family 3-Bedroom Apartment - Abuja Lifecamp",
    description: "Well-appointed apartment with separate living areas, modern kitchen, and secured estate access.",
    price: 210000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 3,
    bathrooms: 3,
    area: 280,
    areaUnit: "sqm",
    location: {
      address: "Life Camp Estate",
      city: "Life Camp",
      state: "Abuja FCT",
      coordinates: { lat: 9.09, lng: 7.39 },
    },
    features: ["Estate Access", "Modern Kitchen", "Gym", "Security"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-19",
    featured: false,
    views: 456,
  },
  {
    id: "17",
    title: "Cozy 1-Bedroom Apartment - Jabi",
    description: "Compact and efficient apartment ideal for singles or couples. Walking distance to amenities.",
    price: 35000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 1,
    bathrooms: 1,
    area: 70,
    areaUnit: "sqm",
    location: {
      address: "Jabi Central",
      city: "Jabi",
      state: "Abuja FCT",
      coordinates: { lat: 9.045, lng: 7.415 },
    },
    features: ["Parking", "Security", "Walking Distance to Mall"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-03-20",
    featured: false,
    views: 123,
  },
  {
    id: "18",
    title: "Duplex Apartment - Mabushi",
    description: "Two-story apartment with separated living spaces, private staircase, and individual parking.",
    price: 520000000,
    currency: "NGN",
    type: "apartment",
    status: "for-sale",
    bedrooms: 5,
    bathrooms: 5,
    area: 500,
    areaUnit: "sqm",
    location: {
      address: "Mabushi Estate",
      city: "Mabushi",
      state: "Abuja FCT",
      coordinates: { lat: 9.06, lng: 7.44 },
    },
    features: ["Duplex", "Private Staircase", "Parking", "Security", "Garden"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-21",
    featured: true,
    views: 789,
  },
  {
    id: "19",
    title: "Retail Shop Space - Jabi Lake Mall",
    description: "Prime retail location with high foot traffic. Equipped with modern fixtures and security system.",
    price: 2500000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 120,
    areaUnit: "sqm",
    location: {
      address: "Jabi Lake Shopping Mall",
      city: "Jabi",
      state: "Abuja FCT",
      coordinates: { lat: 9.044, lng: 7.417 },
    },
    features: ["High Foot Traffic", "Modern Fixtures", "Security", "Parking"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-22",
    featured: false,
    views: 234,
  },
  {
    id: "20",
    title: "Premium Clinic Space - Wuse 2",
    description: "Specialized medical office space with waiting area, consultation rooms, and patient facilities.",
    price: 3500000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 200,
    areaUnit: "sqm",
    location: {
      address: "Wuse 2 Professional Plaza",
      city: "Wuse 2",
      state: "Abuja FCT",
      coordinates: { lat: 9.07, lng: 7.47 },
    },
    features: ["Waiting Area", "Consultation Rooms", "Backup Power", "Parking"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-03-23",
    featured: false,
    views: 145,
  },
  {
    id: "21",
    title: "Bank Branch Space - CBD",
    description: "Grade A office space in the CBD suitable for banking operations with vault-ready infrastructure.",
    price: 8000000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 600,
    areaUnit: "sqm",
    location: {
      address: "CBD Premium Plaza",
      city: "CBD",
      state: "Abuja FCT",
      coordinates: { lat: 9.058, lng: 7.495 },
    },
    features: ["24/7 Power", "Vault Ready", "High Security", "Elevator", "Parking"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-24",
    featured: true,
    views: 567,
  },
  {
    id: "22",
    title: "Restaurant Space - Maitama",
    description: "Spacious commercial kitchen with dining area, private entrance, and liquor license approved.",
    price: 4200000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 350,
    areaUnit: "sqm",
    location: {
      address: "Maitama Commercial Hub",
      city: "Maitama",
      state: "Abuja FCT",
      coordinates: { lat: 9.08, lng: 7.485 },
    },
    features: ["Commercial Kitchen", "Dining Area", "Private Entrance", "Liquor License Approved"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-25",
    featured: false,
    views: 234,
  },
  {
    id: "23",
    title: "Co-working Space - Wuse",
    description: "Modern flexible office with meeting rooms, breakout areas, and high-speed internet infrastructure.",
    price: 1500000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 400,
    areaUnit: "sqm",
    location: {
      address: "Wuse Innovation Hub",
      city: "Wuse",
      state: "Abuja FCT",
      coordinates: { lat: 9.085, lng: 7.46 },
    },
    features: ["Meeting Rooms", "Breakout Areas", "High Speed Internet", "Parking"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-03-26",
    featured: false,
    views: 345,
  },
  {
    id: "24",
    title: "Warehouse Space - Kubwa Industrial",
    description: "Large warehouse facility with loading dock, climate control, and 24-hour security system.",
    price: 5000000,
    currency: "NGN",
    type: "commercial",
    status: "for-rent",
    area: 1000,
    areaUnit: "sqm",
    location: {
      address: "Kubwa Industrial Estate",
      city: "Kubwa",
      state: "Abuja FCT",
      coordinates: { lat: 9.105, lng: 7.36 },
    },
    features: ["Loading Dock", "Climate Control", "24/7 Security", "High Ceilings"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-27",
    featured: false,
    views: 234,
  },
  {
    id: "25",
    title: "Residential Plot - Lugbe",
    description:
      "Corner plot in the peaceful Lugbe area. Perfect for building your dream home with mature neighborhood.",
    price: 320000000,
    currency: "NGN",
    type: "land",
    status: "for-sale",
    area: 1500,
    areaUnit: "sqm",
    location: {
      address: "Lugbe District",
      city: "Lugbe",
      state: "Abuja FCT",
      coordinates: { lat: 8.95, lng: 7.45 },
    },
    features: ["Corner Plot", "C of O", "Tarred Road", "Electricity", "Water", "Peaceful Area"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-28",
    featured: false,
    views: 123,
  },
  {
    id: "26",
    title: "Commercial Land - CBD Extension",
    description: "Strategic commercial plot in the CBD extension area with high development potential.",
    price: 850000000,
    currency: "NGN",
    type: "land",
    status: "for-sale",
    area: 3000,
    areaUnit: "sqm",
    location: {
      address: "CBD Extension",
      city: "CBD",
      state: "Abuja FCT",
      coordinates: { lat: 9.06, lng: 7.5 },
    },
    features: ["High Visibility", "Commercial Zoned", "All Infrastructure", "Flexible Payment"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-03-29",
    featured: true,
    views: 456,
  },
  {
    id: "27",
    title: "Mixed-Use Land - Asokoro",
    description:
      "Large plot suitable for mixed residential and commercial development. Good location and accessibility.",
    price: 1200000000,
    currency: "NGN",
    type: "land",
    status: "for-sale",
    area: 5000,
    areaUnit: "sqm",
    location: {
      address: "Asokoro Extension",
      city: "Asokoro",
      state: "Abuja FCT",
      coordinates: { lat: 9.035, lng: 7.535 },
    },
    features: ["Mixed Use", "Accessible Roads", "C of O", "Development Ready"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-03-30",
    featured: true,
    views: 678,
  },
  {
    id: "28",
    title: "Industrial Land - Nyanya",
    description: "Large industrial plot in the fast-growing Nyanya area with road access.",
    price: 280000000,
    currency: "NGN",
    type: "land",
    status: "for-sale",
    area: 2500,
    areaUnit: "sqm",
    location: {
      address: "Nyanya Industrial Zone",
      city: "Nyanya",
      state: "Abuja FCT",
      coordinates: { lat: 8.9, lng: 7.5 },
    },
    features: ["Industrial Zoned", "Road Access", "Electricity Nearby", "Affordable"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-03-31",
    featured: false,
    views: 234,
  },
  {
    id: "29",
    title: "Agricultural Land - Kuje",
    description: "Spacious agricultural plot in Kuje ideal for farming or investment purposes.",
    price: 85000000,
    currency: "NGN",
    type: "land",
    status: "for-sale",
    area: 8000,
    areaUnit: "sqm",
    location: {
      address: "Kuje Agricultural Zone",
      city: "Kuje",
      state: "Abuja FCT",
      coordinates: { lat: 8.8, lng: 7.3 },
    },
    features: ["Agricultural Grade", "Large Area", "Water Source", "Good Soil"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-04-01",
    featured: false,
    views: 145,
  },
  {
    id: "30",
    title: "Furnished Flat - Garki",
    description: "Fully furnished 2-bedroom flat with modern appliances and immediate occupancy.",
    price: 600000,
    currency: "NGN",
    type: "flat",
    status: "short-term",
    bedrooms: 2,
    bathrooms: 2,
    area: 130,
    areaUnit: "sqm",
    location: {
      address: "Garki I Residential",
      city: "Garki",
      state: "Abuja FCT",
      coordinates: { lat: 9.035, lng: 7.5 },
    },
    features: ["Furnished", "Modern Appliances", "WiFi", "Generator", "Security"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-04-02",
    featured: false,
    views: 234,
  },
  {
    id: "31",
    title: "Executive Flat - Maitama",
    description: "Premium furnished flat with concierge service and premium amenities for corporate clients.",
    price: 800000,
    currency: "NGN",
    type: "flat",
    status: "short-term",
    bedrooms: 2,
    bathrooms: 2,
    area: 150,
    areaUnit: "sqm",
    location: {
      address: "Maitama Premium Residences",
      city: "Maitama",
      state: "Abuja FCT",
      coordinates: { lat: 9.09, lng: 7.485 },
    },
    features: ["Furnished", "Concierge", "Premium Amenities", "Housekeeping", "WiFi"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-04-03",
    featured: true,
    views: 456,
  },
  {
    id: "32",
    title: "Budget Flat - Wuse 2",
    description: "Affordable furnished apartment suitable for students or budget-conscious travelers.",
    price: 350000,
    currency: "NGN",
    type: "flat",
    status: "short-term",
    bedrooms: 1,
    bathrooms: 1,
    area: 80,
    areaUnit: "sqm",
    location: {
      address: "Wuse 2 Affordable Residences",
      city: "Wuse 2",
      state: "Abuja FCT",
      coordinates: { lat: 9.07, lng: 7.475 },
    },
    features: ["Budget Friendly", "WiFi", "Generator", "Security"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-04-04",
    featured: false,
    views: 123,
  },
  {
    id: "33",
    title: "Luxury Flat - Asokoro",
    description: "Upscale furnished flat with premium finishes, personal chef option, and exclusive services.",
    price: 1200000,
    currency: "NGN",
    type: "flat",
    status: "short-term",
    bedrooms: 3,
    bathrooms: 3,
    area: 200,
    areaUnit: "sqm",
    location: {
      address: "Asokoro Luxury Residences",
      city: "Asokoro",
      state: "Abuja FCT",
      coordinates: { lat: 9.035, lng: 7.535 },
    },
    features: ["Luxury", "Personal Chef Available", "Premium Finishes", "Housekeeping", "WiFi"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[0],
    createdAt: "2024-04-05",
    featured: true,
    views: 678,
  },
  {
    id: "34",
    title: "Modern Student Hostel - Off-Campus",
    description: "Well-equipped student accommodation with study rooms, shared kitchen, and recreational facilities.",
    price: 400000,
    currency: "NGN",
    type: "hostel",
    status: "for-rent",
    area: 30,
    areaUnit: "sqm",
    location: {
      address: "Off-Campus Housing",
      city: "Gwagwalada",
      state: "Abuja FCT",
      coordinates: { lat: 8.945, lng: 7.085 },
    },
    features: ["Study Rooms", "Shared Kitchen", "WiFi", "Security", "Recreation Area"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[1],
    createdAt: "2024-04-06",
    featured: false,
    views: 234,
  },
  {
    id: "35",
    title: "Premium Boys Hostel - University Area",
    description: "Upscale male hostel with en-suite bathrooms, study facilities, and gym access on campus.",
    price: 450000,
    currency: "NGN",
    type: "hostel",
    status: "for-rent",
    area: 35,
    areaUnit: "sqm",
    location: {
      address: "University Campus Vicinity",
      city: "Gwagwalada",
      state: "Abuja FCT",
      coordinates: { lat: 8.945, lng: 7.09 },
    },
    features: ["En-suite", "Study Facilities", "Gym Access", "24/7 Security", "WiFi"],
    images: ["/placeholder.svg?height=600&width=800"],
    agent: agents[2],
    createdAt: "2024-04-07",
    featured: false,
    views: 145,
  },
]

export function formatPrice(price: number, currency = "NGN"): string {
  if (currency === "NGN") {
    return new Intl.NumberFormat("en-NG", {
      style: "currency",
      currency: "NGN",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    })
      .format(price)
      .replace("NGN", "₦")
  }
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency,
    minimumFractionDigits: 0,
  }).format(price)
}

export function getPropertyTypeLabel(type: Property["type"]): string {
  const labels: Record<Property["type"], string> = {
    apartment: "Apartment",
    house: "House",
    commercial: "Commercial",
    land: "Land",
    hostel: "Hostel",
    flat: "Flat",
  }
  return labels[type]
}

export function getStatusLabel(status: Property["status"]): string {
  const labels: Record<Property["status"], string> = {
    "for-sale": "For Sale",
    "for-rent": "For Rent",
    "short-term": "Short Term",
  }
  return labels[status]
}
